/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import model.Curso;
import model.Estudiante;

/**
 *
 * @author polares
 */
public class AsignacionCurso extends Vista {

    /**
     * Creates new form AsignacionCurso
     */
    public AsignacionCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cursosLista = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        estudiantesLista = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        asignarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Asignar Estudiante");

        cursosLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Curso");

        estudiantesLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Estudiante");

        asignarBoton.setText("Asignar Estudiante");
        asignarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(cursosLista, 0, 283, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(estudiantesLista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(asignarBoton)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursosLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estudiantesLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(asignarBoton)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void llenarListas() {
        ArrayList<Curso> cursos = getControlador().getModelo().getListaCursos();
        this.cursosLista.removeAllItems(); //Limpio la lista desplegable
        for(Curso curso: cursos) {
            this.cursosLista.addItem(curso.getId()+" - " + curso.getNombre() + " - " + curso.getSeccion());
        }
        ArrayList<Estudiante> estudiantes = getControlador().getModelo().getListaEstudiantes();
        this.estudiantesLista.removeAllItems(); //Limpio la 2 lista desplegable
        for(Estudiante estudiante: estudiantes) {
            this.estudiantesLista.addItem(estudiante.getCUI()+" - " + estudiante.getNombre());
        }
    }
    
    private void asignarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarBotonActionPerformed
        // TODO add your handling code here:
        String seleccionado = (String) this.cursosLista.getSelectedItem(); //Se pbtiene el item seleccionado
        String seleccionado1 = (String) this.estudiantesLista.getSelectedItem(); //Se obtiene el item seleccionadp
        String cursoID = "";
        String estudianteCUI = "";
        //"1001 - IPC1 - A"
        if (seleccionado != null && seleccionado.contains(" - ")) {
            cursoID = seleccionado.split(" - ")[0];
        }
        if (seleccionado1 != null && seleccionado1.contains(" - ")) {
            estudianteCUI = seleccionado1.split(" - ")[0];
        }
        getControlador().asignarEstudiante(cursoID, estudianteCUI);
        getControlador().crearTransaccion(cursoID, "Se asigno al estudiante " + estudianteCUI + " al curso " + cursoID);
        getControlador().mostrarVentana(TipoVentana.Ventana.INICIO);
    }//GEN-LAST:event_asignarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignacionCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignacionCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignacionCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignacionCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsignacionCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignarBoton;
    private javax.swing.JComboBox<String> cursosLista;
    private javax.swing.JComboBox<String> estudiantesLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
