/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.FlujoControlador;
import java.io.Serializable;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author polares
 */
public class VerProgreso extends VentanaBase {

    /**
     * Creates new form VerProgreso
     */
    public VerProgreso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listaAutomoviles = new javax.swing.JComboBox<>();
        listaServicios = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addOrdenBoton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOrdenes = new javax.swing.JTable();
        procesarBoton = new javax.swing.JButton();
        esperaBarra = new javax.swing.JProgressBar();
        servicioBarra = new javax.swing.JProgressBar();
        listosBarra = new javax.swing.JProgressBar();
        labelEspera = new javax.swing.JLabel();
        labelServicio = new javax.swing.JLabel();
        labelListos = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cerrarSesionBoton = new javax.swing.JButton();
        carrosListosLabel = new javax.swing.JLabel();
        carrosListosLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Órdenes de Trabajo");

        listaAutomoviles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaAutomoviles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAutomovilesActionPerformed(evt);
            }
        });

        listaServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Vehiculos");

        jLabel3.setText("Servicios");

        addOrdenBoton.setText("Agregar a Orden de Trabajo");
        addOrdenBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrdenBotonActionPerformed(evt);
            }
        });

        jLabel4.setText("Ordenes de trabajo");

        tablaOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Placa", "Servicio"
            }
        ));
        jScrollPane1.setViewportView(tablaOrdenes);

        procesarBoton.setText("Procesar");
        procesarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarBotonActionPerformed(evt);
            }
        });

        labelEspera.setText("0");

        labelServicio.setText("0");

        labelListos.setText("0");

        jLabel8.setText("Cola de Espera");

        jLabel9.setText("En Servicio");

        jLabel10.setText("Carros Listos");

        cerrarSesionBoton.setText("Cerrar Sesion");
        cerrarSesionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBotonActionPerformed(evt);
            }
        });

        carrosListosLabel.setText("Listos >>");

        carrosListosLabel1.setText("Listos >>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addOrdenBoton)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(listaAutomoviles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(listaServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(100, 100, 100))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(procesarBoton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1)
                        .addGap(145, 145, 145)
                        .addComponent(cerrarSesionBoton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(servicioBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelServicio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(esperaBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelEspera))
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listosBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelListos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(carrosListosLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carrosListosLabel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cerrarSesionBoton))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaAutomoviles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addOrdenBoton)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(procesarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esperaBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEspera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(servicioBarra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelServicio, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(4, 4, 4)
                        .addComponent(listosBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelListos, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carrosListosLabel)
                    .addComponent(carrosListosLabel1))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaAutomovilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAutomovilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaAutomovilesActionPerformed

    private void procesarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarBotonActionPerformed
        // TODO add your handling code here:
        this.getControlador().iniciarFlujo();
    }//GEN-LAST:event_procesarBotonActionPerformed

    private void addOrdenBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrdenBotonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.tablaOrdenes.getModel();
        modelo.setRowCount(0);
       
        String auto = (String) this.listaAutomoviles.getSelectedItem(); //Se obtiene el item seleccionado
        String serv = (String) this.listaServicios.getSelectedItem(); //Se obtiene el item seleccionado
        String carro = auto.split(" - ")[0];
        String servicio = serv.split(" - ")[0];
        //Se manda a crear la orden y se obtiene al cliente para cargar sus ordenes
        Cliente cliente = this.getControlador().crearOrdenTrabajo(carro, servicio); 
        
        Vector<OrdenTrabajo> ordenes = cliente.obtenerOrdenesSinAsignar();

        Vector<String[]> ordenesRow = new Vector<String[]>();
        for(OrdenTrabajo orden: ordenes) {
            ordenesRow.add(new String[]{ orden.getId(), orden.getPlaca(), orden.getServicio() } );
        }
        
        //Llenar la tabla
        for (String[] orden : ordenesRow) {
            modelo.addRow(orden);
        }
    }//GEN-LAST:event_addOrdenBotonActionPerformed

    private void cerrarSesionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBotonActionPerformed
        // TODO add your handling code here:
        Cliente c = this.getControlador().obtenerCliente(this.getControlador().getUsuarioActual());
        c.getVentanaProgreso().setVisible(false);
        this.cerrarSesion();
    }//GEN-LAST:event_cerrarSesionBotonActionPerformed

    
    public void llenarListas() {
        Vector<Automovil> autos = this.getControlador().obtenerAutos(this.getControlador().getUsuarioActual());
        this.listaAutomoviles.removeAllItems(); //Limpio la lista desplegable
        for(Automovil auto: autos) {
            this.listaAutomoviles.addItem(auto.getPlaca()+" - " + auto.getMarca() + " - " + auto.getModelo());
        }
        Vector<Servicio> servicios = this.getControlador().getModelo().getListaServicios();
        this.listaServicios.removeAllItems(); //Limpio la 2 lista desplegable
        for(Servicio servicio: servicios) {
            this.listaServicios.addItem(servicio.getId()+" - " + servicio.getNombre());
        }
    }
    
    public void vaciarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) this.tablaOrdenes.getModel();
        modelo.setRowCount(0);
    }

    public JProgressBar getEsperaBarra() {
        return esperaBarra;
    }

    public void setEsperaBarra(JProgressBar esperaBarra) {
        this.esperaBarra = esperaBarra;
    }

    public JProgressBar getListosBarra() {
        return listosBarra;
    }

    public void setListosBarra(JProgressBar listosBarra) {
        this.listosBarra = listosBarra;
    }

    public JProgressBar getServicioBarra() {
        return servicioBarra;
    }

    public void setServicioBarra(JProgressBar servicioBarra) {
        this.servicioBarra = servicioBarra;
    }

    public JLabel getLabelEspera() {
        return labelEspera;
    }

    public void setLabelEspera(JLabel labelEspera) {
        this.labelEspera = labelEspera;
    }

    public JLabel getLabelListos() {
        return labelListos;
    }

    public void setLabelListos(JLabel labelListos) {
        this.labelListos = labelListos;
    }

    public JLabel getLabelServicio() {
        return labelServicio;
    }

    public void setLabelServicio(JLabel labelServicio) {
        this.labelServicio = labelServicio;
    }
    
    public void llenarCarrosListos(Cliente c) {
        this.carrosListosLabel.setText("");
        for(OrdenTrabajo o: c.getListaOrdenes()) {
            if(o.getEstado() == 3) {
                this.carrosListosLabel.setText(this.carrosListosLabel.getText() + " " + o.getPlaca());
            }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerProgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerProgreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrdenBoton;
    private javax.swing.JLabel carrosListosLabel;
    private javax.swing.JLabel carrosListosLabel1;
    private javax.swing.JButton cerrarSesionBoton;
    private javax.swing.JProgressBar esperaBarra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEspera;
    private javax.swing.JLabel labelListos;
    private javax.swing.JLabel labelServicio;
    private javax.swing.JComboBox<String> listaAutomoviles;
    private javax.swing.JComboBox<String> listaServicios;
    private javax.swing.JProgressBar listosBarra;
    private javax.swing.JButton procesarBoton;
    private javax.swing.JProgressBar servicioBarra;
    private javax.swing.JTable tablaOrdenes;
    // End of variables declaration//GEN-END:variables
}
